apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: host-zfs
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
parameters:
  recordsize: "128k"
  compression: "lz4"
  dedup: "off"
  fstype: "zfs"
  shared: "yes"
  poolname: "zfspv-pool"