apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password
stringData:
    PASSWORD: ENC[AES256_GCM,data:9aBzhjdjMMU=,iv:fKslSJpmk79Mz/pr55SpO1fp4PvEx+diFiiei+88hxM=,tag:ej3A0cwCtRlPRCyqHHBL/g==,type:str]
sops:
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRXcySXg4eHlEUDN3WTN2
            cHFTRGk5N1pGTmxvSExiQmorRVA2T2Q2MVJNCnRCWndMVWIzcGVDYXNhekpTei9B
            NGY4N01uWExUZHZmcTU5d0t6bTIya2sKLS0tIDlubjB2TUlIZHVuTkdtaEl4S3pE
            OHgxdFczVjd5KzRBSUhienJKbThSMncKWlm9Ncwgp1Q9b17Uwj+GidYgsrjGL6Kv
            yAloCGFSepOUULJEGBHllxas9GmmsijFQHVspH2HyfFqjmfP+xzVYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T12:09:52Z"
    mac: ENC[AES256_GCM,data:ER4ToeMo/mQ5oW5hPbblnnV/rSFFh6+8EAgjts55Ml2K5SIFAtsVgtFYw1PEXh8Tjmorm1OMa840AQhpfPlkllRqXrSgOT/GuBEc45p9lnBPGOdmmup4XmYH30NkZpZdnCUeQhRkzlMihoX5vt0wFriBKYASKw/W4a+7moUOPrQ=,iv:tCQdvrzmZzRNB6xjl67DRcLgfpDfyHJcM966DrWb7Ho=,tag:cusnq0PInJLR/YzYxEGc1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
