---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  dependsOn:
    - name: openebs
  interval: 10m
  path: ./kubernetes/apps/media/paperless/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  targetNamespace: media