apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - podmonitor.yaml
configMapGenerator:
  - name: flux-grafana-dashboards # https://github.com/fluxcd/flux2-monitoring-example/tree/main/monitoring/configs
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled