apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lp-downloads
  namespace: media
  labels:
    app.kubernetes.io/name: config
    app.kubernetes.io/instance: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: host-zfs
  resources:
    requests:
      storage: 50Gi