apiVersion: v1
kind: Secret
metadata:
    name: tandoorrecipes-secret
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:Yk7k9woGCRMM3Ekiyz+vzw4vx7XufSmf4GrXRpZ1tOsgid5OWwkFNMWn0qL/OCVIb5U=,iv:WIoPtOg6rSh5iJYvdKPxJfDocTm2/k1z1BHEiRtiHRM=,tag:ZEwzIJB0gZ8BKjqYj8YPMA==,type:str]
sops:
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMmhINHc4MnpoMXdFRkp3
            MjU5MGs4elJ3VFU4ZkVlS0JaTWlobWxOaUFnCjZsWkVld0VyREhoT1R2RzlPYXBY
            VFdiRjhlKy9yUlB4aUxzeU5VNVdJb2MKLS0tIHMzbldUOGo5UmM2S0FXeDVFekIy
            d1JiS01zVWNpNnlUNGtkMm5nRnNnYzQKj1neFm1kK5RGZxfPo4iUblKf1az2vpWN
            xrbD2kBTgJAds5J5XvH6IN+qYum1Y17AcHuKjKytG1SqO3TQYS4zUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T17:24:40Z"
    mac: ENC[AES256_GCM,data:sCzMNVj4q/eMSkTKVXUqYgmhRIG3MpVzbAxWyjqxdW2oSw7irGjzlIskfx3IMNnY6mhUCQl1AEhL/QxP2QlJLtiUnQmAda2u435uzy0NIx4a62DYiT/BZbhsSujqTf5L2oOw7haWHgJoapkLUPbfRPepGnsxjHLioaMTIXDiDwQ=,iv:idc0kTGG9R6uvC+eByyVoF9Z2O9nbIl4JE2Pbzoh9VE=,tag:gaQ1nwWxCwR4f2jkAO9uTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
