apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:pKfV1/48xq2c5KtJlvxgIm5yjHKpuhG5yvt0lDSkeqHlJclqdqdY4anxt4lcoXseKq1rxIerd9iStODo8P+ukg==,iv:7GLVVZUxcgZwWrDcHCjB1wG2c/lPkIEbNGNdnu1SNtY=,tag:GI7k/rvpSWyX40IGF02pWg==,type:str]
sops:
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMDg0eUNqSmh5aUpzaVpi
            blpPT3lWeGcwZUs1RWcwYjVHaFQ2K2R6ekEwCmVoaWd2N3hzcDhGVWhLRk1tQ2lR
            SWZycm02NEtFZWNZRjFzQXcwQnJocE0KLS0tIFVoWEdENCtCdVdOSHl4STlzSmt0
            dHBoTHdSNk50ZzQyeHFrTk44MHNsMTQKFx06IgpeQ7+5elV2BpRTybCXUjnJogtn
            Fmfatm4g2DKUIcNlb6nHkrgKGdqC2CdBQSiNX9TnrHCQklTkhrRuPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T19:24:27Z"
    mac: ENC[AES256_GCM,data:G2z3ajAH2A2ms2fk80mxA65ss7yoHGxGE9M/GBze76nf+kR0W/81+Iznyo/NAgU7iYT1cxq2FJLI/kp3AcudkU+1GV2wdLTh5pAQ4U4wJuIyEGaepjftHXEzepn1UixITHYoLzixC9Pf3c3bIYqwB7TJtWiylNdN0OeEyJQv74o=,iv:ZyBUnVwb0OzNaVVuBgNk3IbmmtfkcE826luruCGS3Mg=,tag:ZyGKOwk819pcJVl70EigDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
