apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:UDbFY/hrneyc45kUo8OleImLNSazJ19DcA7hahxdCTMX2K+4GDGHsQkrp6MhgkuUxNTFxivkgQiWizqYc2FbDg==,iv:Kb+fMwdgNVYn8dmSdYrNZ7kCwFzJo6/mqaSzpGu+NxE=,tag:G3rCuilRnqIcZnEf+aqCSQ==,type:str]
sops:
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUXBhVFYydC95ZzJLa09q
            VFdQaENlUGFhMnI1dTdrTncyZTNSb3FqbUFFCnM4SGphck50SmUwUkZodjNkRlor
            K0g0ZGIyQmZvWUxTMjQ2SlhSOVFzdHMKLS0tIFBUeWk5MVFFVlkzMzRTbmFDeW9w
            K0FadjZaTzNjUXc0TUxwRW5aYzdvaDQKVAFqY8NJ2zBm+Alm/1dNZl2i/maAjpJN
            XqIpjABm9Q4yXT5fn7Oi2VyZV3wnyX7cB47kgV6vjyM8prQzlYBZ9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T11:43:21Z"
    mac: ENC[AES256_GCM,data:UfDYVP1s1VVpkeOiyPdUHgv6GkJPaqaWb4H61HuTdMTXemWmiOAPtzMa6M8erF9xC2L+z5nx0fxQgegPCvwRallhybZtShjpM5lAA+IbfMjF43MExYcYaTUZwbzoDrvV6At/G/yYaHBRdEPqKxssD7qHC99RK1DMFCgLWNYW+/0=,iv:Pwe3C6msY8pW9TsTdOxJbJhPwPivJVhlqiYvaPegjTg=,tag:dlMsBHfkrj3DotGvXD5qsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
