---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: volsync
  dependsOn:
    - name: openebs
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: volsync
      namespace: system
  interval: 10m
  path: ./kubernetes/apps/system/volsync/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  targetNamespace: system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync-maintenance
  namespace: flux-system
spec:
  dependsOn:
    - name: volsync
  interval: 1h
  path: ./kubernetes/apps/system/volsync/maintenance
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  targetNamespace: system
  wait: false