apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance-secret
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:oeE3JW4RTbh+CTc=,iv:smc2Cnu2ZaRdI1/5wMxGpp7FxK/LSPM2RdRGddmE5ec=,tag:VrYvZYdZfirP+pAdm404Gg==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:woPRzE2t0Vu7iCPFIOzP7FWNsspzfK8A,iv:YESHhYb0n8t6+ecbTeFMv9BycpklSAHZNY80+npDyDQ=,tag:czHra15beKx/m7g4DVZwNg==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:NesmJ17Y1rARzo2lCzjjmmGLzPSK/wyIKfbgjLEy2Q+2oIXHwM+nhZCBGNT2/OH8//WIUb221YKifbrwD/QQAw==,iv:Fe62qDatEfsx0SlKahnl58PGQhuCZl7iBFTfnrg9Tu8=,tag:vltBSpSOvLB8OBV7rTh6yg==,type:str]
sops:
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRjFuaWYydllvQXhzVTAr
            OXIxWEpUdWFxNnJHVitPQ1l4cjJydkZTa3kwCjd0cjdNSVFVZFJkV0x1Z2I0c3gy
            WmZMNzVUaVk0UHlzamJRQ1F0N2ppL3cKLS0tIFlha2x5N3U5S21DOHRvREtYSWZD
            bmhIVUxpRk9wMjFSNDg4clYrbUN3ZVkKOwECRrU/AjvFn82Mk3mQmrFnZvJTH866
            qS0BL29d5VMZbDCIFTo/sIR0vBLWEJb9s4gi+pB5YJl06m4MVjta6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T19:24:55Z"
    mac: ENC[AES256_GCM,data:NTxnj8NBY3tSV7ob0deBsQKIQGwPC+FmJf1fWrgLm0miGuXvwO6plsCGn8o/YD92gRZTYyzlwWyZnhhe0VaZmgyWUyi7AbgMl0EoRNasaQe9htH5BP9D47ajY8ykw8/xy3BUVxXrRc7d9Y69b47iRwcUj1+5UZnkMtZUhFeigyY=,iv:YIRKDpcnUnBgAb3IAK8dK1jbq05zD0EaBC5TDDjVFdA=,tag:is9KJJe5LG0JvsyiUQFhKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
