apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:o2dr9ls=,iv:bZERsd/P7Drahdp7CHs/z9swZP9cRwZmr/4zH2+dWgc=,tag:P/zyngap/R9Z3iJm2EVYFA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:48wa+KbyYYs=,iv:HfLj7kvAkRcf3Be/lvHNJM3NdOWLLsvIjJPbA1Gj14k=,tag:YQlBBxEaefWxSpAycWhPig==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:Or+y8SSLE18hjHN85iTh+uzpbVrHAu8LU19XeXPz+DLFMba+V7/MeJ2boybqTPmfK87L3xqq1PQEi1ik95Cafw==,iv:pge6FixulthGZweeAUQwbxsN0VmNnPw3r0JP1eOc+A4=,tag:kPo5yWcnXdHAiMS23g/4Zg==,type:str]
sops:
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpY2x4R1RpSytBcDcraWdL
            ODNFa0FwaWs4aExHTHNoY0h3T1gxSXdva2h3CktwQzhPOTgzbnB3MnEzTGlMU1JV
            Uyt0R212MjRzUlhxVkdjQUpWZUZOaUUKLS0tIGZrZEpieU5UUFQ4amxRWStaQzc4
            MWVGTWpCMll0cGVVUU94Vk9IaHF0NVEKFZJvQPDnHSSIg0wG/r66u+wSzOfQIb6t
            uHkAEGnrPxY4bgU5y0OROZPqxZMRiMyuAGb9B/Y9K3s62VKbtr8Lsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T17:00:43Z"
    mac: ENC[AES256_GCM,data:ntLuCPCzRhM3bVJPTGS8ujVVVbWL8p3dpR6H0IyUI2OnnvswJ+QU2bPnr4gj1ALuG8xG6cIgSbhJDz3LOnOhsiBJVciD+aZrc09YZqNG3X01Sx9ozFiiUWXj3rXfEkngjivhSJIfzWamsA/Qylm85T3R33vb8mx0zgAF7gFtO40=,iv:0EsWY3TXqqbh+KftLwY33H2pR1jU6D0w0uLXKG/Xv0A=,tag:ezpenjMA2svbZmiEONHTPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
