apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:vtNlUZt2nK+ijlY=,iv:WTVm/IWOwFjphHCD5FPeeSpwSbcsjZ962BPSyj+3mLU=,tag:cbPYpgiUARvIIs91fcqYgg==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:5a1hFNchK99oWTyuhcvvFX/3iQSXFHLR,iv:OoGI7njf+wNSTYyFlIdDG7pUGKGSkrZHXidL3C+ZJ/s=,tag:GotID/zQMIXkp6uef2jl+w==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:W+atkVsZj6JV1LjN+bWy8GopEnclZCIG4BZw7rbha+kos7WV9uw9plt2ixVlMBNsVmjoUqYkj6mh0HHkB9MJnw==,iv:sW9/q3CkxyZ+rTPpJGEcNVrQTa7sE9hbKw/1y0asiuc=,tag:pu0wiv44QfoqSpRMLxcr2A==,type:str]
sops:
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVkszZUNUR0Z3ZmFDdWpi
            Z3d2aHl1ODJ4ZFZyWDB5elpVYmgxODlvNHkwCldYbGorbzBLVnJ0TncwVnhpd3NG
            Q2tOYk5VQlV3bzA2VXdOTW9uU1NDc1kKLS0tIE1zODlDcDdzYko4K1lqck8zUzFV
            dXkxRzNWWXI5WEFBMjV3OXQ2Zm9HRkUKI0obCgf2swJHlcVSt8Vl0dR3vlYL9I1D
            Qy6Gya8ZZLz/FJa+Mlu6G8DkYtYo9QRigS2xma/A6d8NnmzpsGmGxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T14:03:26Z"
    mac: ENC[AES256_GCM,data:qC4B5/ifnCaQJkk5jq2L061qDtykGZorwHZKF53Q70gH4RNC+Do7HMvpTpGLSESs+FFJ0p13Aivs/RyiyyfqrrNHrjd7F0r/HH5jiTNjDb7p4ZPHrAITKueJs7CYWJhIt4KhKiCgDo0QFQ89+Diodhn+/40dLJDLooxiObYyep4=,iv:Dk5vkWzXSAq2zxmPu4MgtJ9KXV62gmscapeY39adfbA=,tag:gULoTEnR0yCBnOrk83qsBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
