---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
spec:
  chartRef:
    kind: OCIRepository
    name: homeassistant
  interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2026.2.3@sha256:96fa92d83fa8dae987fbbbcf58b1fea1140985ff6a8517b37f7b65c76ef20133

    service:
      main:
        ports:
          http:
            port: 8123

    route:
      main:
        hostnames:
          - "hass.muellner.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      configuration-file:
        type: configMap
        name: homeassistant-config
        globalMounts:
        - path: /config/configuration.yaml
          subPath: configuration.yaml
      config:
        existingClaim: homeassistant-config
        globalMounts:
        - path: /config
      binary-sensor-file:
        type: configMap
        name: homeassistant-binary-sensor
        globalMounts:
        - path: /config/binary_sensor.yaml
          subPath: binary_sensor.yaml
      sensor-file:
        type: configMap
        name: homeassistant-sensor
        globalMounts:
        - path: /config/sensor.yaml
          subPath: sensor.yaml
      template-file:
        type: configMap
        name: homeassistant-template
        globalMounts:
        - path: /config/template.yaml
          subPath: template.yaml
