---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: seerr
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: openebs
  interval: 10m
  path: ./kubernetes/apps/media/seerr/app
  postBuild:
    substitute:
      APP: seerr
      VOLSYNC_CAPACITY: 1Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  targetNamespace: media
