---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana.yaml
  - ./grafanadatasource.yaml
  - ./httproute.yaml
  - ./grafana-credentials.sops.yaml
  - ./servicemonitor.yaml