---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
data:
  # URLS
  IMMICH_WEB_URL: http://immich-web.media:3000
  IMMICH_SERVER_URL: http://immich-server.media:3001
  PUBLIC_IMMICH_SERVER_URL: "https://immich.muellner.dev"
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media:3003
  
  REDIS_HOSTNAME: "immich-valkey.media"
  REDIS_PORT: "6379"
  DB_HOSTNAME: "immich-database.media"
  DB_PORT: "5432"

  # General
  NODE_ENV: "production"
  LOG_LEVEL: warn