apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./secret.sops.yaml
  - ./configmap.yaml
  - ./pvc-photos.yaml
  - ./pvc-ml.yaml
commonLabels:
  app.kubernetes.io/name: immich
  app.kubernetes.io/instance: immich