apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./cluster-secrets.sops.yaml
  - ./cluster-settings.yaml
  - ./grafanadashboard.yaml
  - ./podmonitor.yaml
