apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./reloader/ks.yaml
  - ./openebs/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./kopia/ks.yaml
  - ./volsync/ks.yaml
  - ./snapshot-controller/ks.yaml