---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopia
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kopia
  dependsOn:
    - name: volsync
      namespace: system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kopia
      namespace: system
  interval: 10m
  path: ./kubernetes/apps/system/kopia/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  targetNamespace: system
