---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: zigbee2mqtt
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: openebs
  interval: 10m
  path: ./kubernetes/apps/home-automation/zigbee2mqtt/app
  postBuild:
    substitute:
      APP: zigbee2mqtt
      VOLSYNC_CLAIM: zigbee2mqtt-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  targetNamespace: home-automation
