apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
stringData:
    PASSWORD: ENC[AES256_GCM,data:26513Fk23/E=,iv:kcZkv0e8H6gmUq90h5ay65ekbZf3wMVf6S3z9hmyJW0=,tag:CicU+iLFBERTdfT2cjPYKA==,type:str]
sops:
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdGRtd2krWVFzUisvaVE2
            ZzlySmt0NFZZMjJGY250RERhYjFDTitHeFQ0CnJMMjNlcEVSbkF0NHZoc2tHRW9E
            S1lRWWIwOGllUTBjT1czNmpzTC9GbFUKLS0tIGllV2I4TjFqWmw4L0gwc2lKb3BQ
            ZVdrTGJPaW5nbVlpUEp4alliS2ladmcKt3JFMt+b9FqcHum5lsGRPkwSW5yEJiP2
            wdVzH1Y67e62Q2EdKZyD/PPCxJRCDcp4qaZOXH/f8EFCndEihCeEVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T11:03:42Z"
    mac: ENC[AES256_GCM,data:EDxzFVVM9UCluCc4cev78bnxLzXsloOq0V8ej+x/mh0kcZkt+3IoVSnk8NMmW2QZcMLKK6ZPnWvHrqRpNFMmip+5vfEXKiafnk4+T6YgPB0WGRihjvza9t+YB2m2itbM2UWDPvtwk0SURGwCw9inplP/Ym0didgVrZfktRV5zlM=,iv:y0diRSdTdve88/zch3b1eF8D8I/Dd+BblWdJJAceBhc=,tag:ubOKK3taczAtqkBS3e0VDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
