apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
stringData:
    PASSWORD: ENC[AES256_GCM,data:JPEfBkJs,iv:GGNsqw8SibRqnJIofKQ+1OMCJOhKNhr514dwIP6jFX8=,tag:gcU4LNIXqw2Dis1wL5Ndfg==,type:str]
sops:
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISE1icnVXdzg5S0dHRDhs
            UWhDRkFmQk5FQ284Ynh1YktsNTh4NmxuMlRzClhsWDdtWnVWTmt3UDVUUWhVb1Q3
            S3dYaE5nVEJhNDN1RWRRQkt1a1RhM1EKLS0tIEtwWEJEZnBxc0VhVVZaWlZYMFBH
            SU1CVnJkQlg3cmZrUU95S01NcjFSdzgKE+qhYVhbpCZ4fCXOgKgYU7sQfcJi3/WH
            MJphXjl266aCEsbyA9UsGIqWbSV6IQ4kyS7PJB4RGxY0sTCirO9ABg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T11:27:03Z"
    mac: ENC[AES256_GCM,data:pvkxe1h5P0vmla5RSfBjtBAB3NR56kjgEgpVaD2JF/u7MNtk2U1oXJysuIGMMVJ74zAPy7l6ynJeSwF9N5m/fG29USceIf8hCyMm++APXeU1otABnvVVfXowd3Q6+u86ig6zElvbkMN3G91djE/LXn23zmlkL36F4HuVUOMfKI4=,iv:qBpGHuhGIQddE6I2fDtM5sC4dc4atM9Eu5Y7V9gfP4g=,tag:ahIbJ9rynOzBVgovc+olCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
