---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tandoorrecipes
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: tandoorrecipes
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: volsync
  interval: 10m
  path: ./kubernetes/apps/selfhosted/tandoorrecipes/app
  postBuild:
    substitute:
      APP: tandoorrecipes
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  targetNamespace: selfhosted
